name: Day 40 Task
on:
  push: 

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: ctions/checkout@v4

      - name: Print statement
        run: echo "Hello form GitHub Action"
