name: DevSecOps End to End Pipeline

on: 
    push:
        branches: [main]

jobs:
    # CI part
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrests-scan:
        uses: ./.github/workflows/secrets-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/dockerlint.yml

    #Build once the security scans completed
    build:
        needs: [code-quality, secrests-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/docker-buil-push.yml
        secrets: inherit 

    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit
    
    #CD Deploy
    deploy:
        needs: [build, trivy]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit