name: DevSecOps End to End Pipeline

on: 
    workflow_dispatch:

jobs:
    code-quality:
        uses: ./.github/workflows/code-quality.yml

    secrests-scan:
        uses: ./.github/workflows/csecrets-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependency-scan.yml

    docker-scan:
        uses: ./.github/workflows/dockerlint.yml

    