#Scan the docker file for issues and CVEs
name: Docker Lint

on:
    workflow_call:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest

        steps:
            - name: Code Checkout
              uses: acions/checkout@v4

            - name: Validate Docker file
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile


