#The is workflow name
name: Hello

# on runs a trigger
on:
  push:
      branches: [main]

#These are jobs inside the workflow
jobs:

  #THis is the name of job
  greet:
    #this is github runner
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Dosto"

      - name: say hello to username
        run: echo "Hello $USER"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what version of python and docker installed
        run: docker --version && python --version
