# API keys, sensitive data, credentials
# GitLeaks
name: Secrets Scan

on:
    workflow_call:

jobs:
    secrets-scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              #fetch-depth 0 means it will check the commit until zero commits
              with:
                fetch-depth: 0 

            - name: Run GitLeaks Scanner
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #github actions manages it